[build]
command = "yarn build:lambdas"
functions = "lambdasbuild"
environment = {
  MONGODB_HOST = "herpderp",
  MONGODB_PORT = "",
  MONGODB_USER = "",
  MONGODB_PASS = "",
  MONGODB_DB = "",
  S3_BUCKET_NAME = "",
  S3_REGION = "",
  S3_ACCESS_KEY_ID = "",
  S3_SECRET_ACCESS_KEY = ""
}
