[build]
command = "yarn build:lambdas"
functions = "lambdasbuild"

[build.environment]
PROD_MONGODB_HOST = "MONGODB_HOST_PLACEHOLDER"
PROD_MONGODB_PORT = "MONGODB_PORT_PLACEHOLDER"
PROD_MONGODB_USER = "MONGODB_USER_PLACEHOLDER"
PROD_MONGODB_PASS = "MONGODB_PASS_PLACEHOLDER"
PROD_MONGODB_DB = "MONGODB_DB_PLACEHOLDER"
PROD_S3_BUCKET_NAME = "S3_BUCKET_NAME_PLACEHOLDER"
PROD_S3_REGION = "S3_REGION_PLACEHOLDER"
PROD_S3_ACCESS_KEY_ID = "S3_ACCESS_KEY_ID_PLACEHOLDER"
PROD_S3_SECRET_ACCESS_KEY = "S3_SECRET_ACCESS_KEY_PLACEHOLDER"
