[build]
command = "yarn build:lambdas"
functions = "lambdasbuild"
environment = { MONGODB_HOST = "MONGODB_HOST_PLACEHOLDER", MONGODB_PORT = "MONGODB_PORT_PLACEHOLDER", MONGODB_USER = "MONGODB_USER_PLACEHOLDER", MONGODB_PASS = "MONGODB_PASS_PLACEHOLDER", MONGODB_DB = "MONGODB_DB_PLACEHOLDER", S3_BUCKET_NAME = "S3_BUCKET_NAME_PLACEHOLDER", S3_REGION = "S3_REGION_PLACEHOLDER", S3_ACCESS_KEY_ID = "S3_ACCESS_KEY_ID_PLACEHOLDER", S3_SECRET_ACCESS_KEY = "S3_SECRET_ACCESS_KEY_PLACEHOLDER" }
