// flow-typed signature: 348b2529d088c635932abbf7db7acfbd
// flow-typed version: <<STUB>>/apollo-server-lambda_v^1.3.6/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-server-lambda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-server-lambda' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-server-lambda/dist/index' {
  declare module.exports: any;
}

declare module 'apollo-server-lambda/dist/lambdaApollo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-server-lambda/dist/index.js' {
  declare module.exports: $Exports<'apollo-server-lambda/dist/index'>;
}
declare module 'apollo-server-lambda/dist/lambdaApollo.js' {
  declare module.exports: $Exports<'apollo-server-lambda/dist/lambdaApollo'>;
}
