// flow-typed signature: 88a503023def76409fbab630d942ffbb
// flow-typed version: <<STUB>>/flow-aws-lambda_v^1.0.3/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-aws-lambda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-aws-lambda' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'flow-aws-lambda/index' {
  declare module.exports: $Exports<'flow-aws-lambda'>;
}
declare module 'flow-aws-lambda/index.js' {
  declare module.exports: $Exports<'flow-aws-lambda'>;
}
